language: python

python:
  - "3.7"

sudo: required

dist: xenial

before_install:
  - sudo apt-get update
  - sudo install unzip
  - sudo pip install --upgrade pip
  - sudo pip install -U selenium
  - sudo pip install bs4
  - sudo pip install requests
  - wget https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip --no-check-certificate
  - unzip chromedriver_linux64.zip
# command to run tests
script: 
  - sudo pip install selenium
  - python3 verify.py