language: python

python:
  - "3.7"

sudo: required

dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install unzip
  - sudo pip install --upgrade pip
  - sudo pip install -U selenium
  - sudo pip install bs4
  - sudo pip install requests
  - wget https://chromedriver.storage.googleapis.com/73.0.3683.20/chromedriver_linux64.zip --no-check-certificate
  - unzip chromedriver_linux64.zip
  - pwd
  - ls -al
# command to run tests
script: 
  - python2.7 verify.py