language: php

sudo: required

dist: trusty
php:
  - "7.1"

python:
  - "3.7"

cache: pip
before_install:
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:jonathonf/python-3.7
  - sudo apt-get install python3.7
  - sudo apt-get install unzip
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
  - python3 --version
  - sudo pip install --upgrade pip
  - sudo pip install selenium
  - sudo pip install bs4
  - sudo pip install requests
  - wget https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip --no-check-certificate
  - unzip chromedriver_linux64.zip
  - pwd
  - pip --version
# command to run tests
script: 
  - python3 verify.py