language: php

sudo: required

php:
  - "7.1"

python:
  - "3.7"

cache: pip
before_install:
  - sudo apt-get update
  - sudo apt-get install python3.7
  - python -V
# command to run tests
script: 
  - verify.py