language: python

python:
  - "3.7"

sudo: required

dist: xenial

cache: pip
before_install:
  - sudo apt-get update
  - python3 --version
  - sudo pip install --upgrade pip
  - sudo pip install selenium
  - sudo pip install bs4
  - sudo pip install requests
  - wget https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip --no-check-certificate
  - unzip chromedriver_linux64.zip
  - pwd
  - pip --version
# command to run tests
script: 
  - python3 verify.py