language: php

sudo: required

php:
  - "7.1"

python:
  - "3.7"

cache: pip
before_install:
  - sudo apt-get install unzip
  - sudo apt-get -y install python3.7
  - python3 --version
  - sudo pip install --upgrade pip
  - sudo pip install selenium
  - sudo pip install bs4
  - wget https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip --no-check-certificate
  - unzip chromedriver_linux64.zip
  - pwd
# command to run tests
script: 
  - python3.7 verify.py