language: php

sudo: required

php:
  - "7.1"

python:
  - "3.7"

cache: pip
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - python -V
# command to run tests
script: 
  - python verify.py